production:
  method: local

development:
  method: daarmaan
  host: "http://localhost:9000"
  login_url: "/authenticate/"
  logout_url: "/logout/"
  login_page: "/"
  service_name: "nersi"
  service_key: "123456"
  
